
var c = 1
var e = 2


while (c <= 5) { //WHILE - Enquanto a variavel c for menor ou igual a 5, continue executando em loop.
    console.log(c)
    c++
}



do {
    console.log(e)
    e++
} while (e <= 10) //DO WHILE - irá primeiro executar e depois verificar se é verdadeiro ou falso. Enquanto a variavel c for menor ou igual a 5, continue executando em loop.



for(var c = 1 ; c <= 5 ; c++) { //ESTRUTURA DO "FOR" = for (var ? = ? ; TESTE LÓGICO ; INCREMENTO (C++, por exemplo)). Enquanto a variavel c for menor ou igual a 5, continue executando em loop.
    console.log(c)
}